image: node:10.15.0
    
pipelines:
  custom: # Pipelines that are triggered manually
    sonar: # The name that is displayed in the list in the Bitbucket Cloud GUI
      - step:
          script:
            - echo "Please Give me a $REPO_VAR_00"
            - git clone git@github.com:jasonyahoo/soongone.git
            - apt-get update -y
            - apt-get -y install rsync
            - rsync $BITBUCKET_CLONE_DIR/ -av --exclude=".*" soongone/
            - cd soongone
            - git config --global user.name $EXT_GIT_USR
            - git config --global user.email $EXT_GIT_EMAIL
            - git add .
            - git commit -m "Automated Commit from BB"
            - git push

